sudo: required

services:
    - docker

language: go

go:
  - 1.5

script:
  - chmod +x build.sh && sh build.sh

deploy:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD" 
  - docker push openservice/acl-service:latest
